### ISSUE TITLE
请修改这里的名称

### ISSUE THREAD

**Issue by Yan5zpky** [TechXueXi/techxuexi-js#29]
### 清单

- [X] 我已经仔细阅读过 README 说明 https://github.com/TechXueXi/techxuexi-js
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/techxuexi-js/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 脚本名称

不学习何以强国.js

### 软件/源码版本

20210125

### 系统版本，包含位数

windows10 x64

### 浏览器版本

edge

### 油猴等插件和它的版本

油猴 v4.11

### 详细描述

js脚本里引用的两个js资源被屏蔽了，需要更新一下。
https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js

**Comment by techxuexi21** [comment]
@Yan5zpky 现在脚本里的是这个啊，是这个也被屏蔽了吗？

**Comment by 398371905** [comment]
// @require      https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
// @require      https://cdn.jsdelivr.net/npm/blueimp-md5@2.9.0

可以用

**Comment by techxuexi21** [comment]
@398371905 这个大部分地区被和谐了

**Comment by techxuexi21** [comment]
@techxuexi21 是 cdn.bootcdn.net 服务问题，原因还不知道

**Comment by Yan5zpky** [comment]
> @techxuexi21 是 cdn.bootcdn.net 服务问题，原因还不知道

之前能用，现在不能用，是这个cdn资源库的服务问题吧，我换了别的源的js资源就可以用，我临时用的菜鸟教程的，md5那个我找不到，用的github的源

**Comment by zhutie-oldsuperman** [comment]
--> 当前ChromeDriver版本号和Chrome浏览器版本号不一致，准备进行更新
Traceback (most recent call last):
  File "operation\get_chromedriver.py", line 29, in do
  File "operation\get_chromedriver.py", line 56, in get_download_version
IndexError: list index out of range

--> 程序异常，请确保你的chrome浏览器是最新版本，然后重启脚本
请按任意键继续. . .

**Comment by wjw020206** [comment]
建议更新一下脚本试试，现在最新版本号为20230318
