### ISSUE TITLE
采用pushplus无法收到二维码登录推送了，但是增加新用户请求可以收到

### ISSUE THREAD

**Issue by BoyleZhao** [TechXueXi/techxuexi-js#55]
### 清单

- [X] 我已经仔细阅读过 README 说明 https://github.com/TechXueXi/techxuexi-js
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/techxuexi-js/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 脚本名称

不学习何以强国.js

### 软件/源码版本

20220126

### 系统版本，包含位数

respberrypi 3B+ 32位armv7

### 浏览器版本

chrome v73.0.0

### 油猴等插件和它的版本

 v4.11

### 详细描述

欢迎使用 TechXueXi
[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20220126
[*] 最新版本为：v20220126
正在打开二维码登陆界面,请稍后
Exception in thread 开始学xi:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/xuexi/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "/xuexi/pandalearning.py", line 73, in start_learn
    cookies = driver_login.login()
  File "/xuexi/pdlearn/mydriver.py", line 282, in login
    cookie_list = self.get_cookie_from_network(chat_id)
  File "/xuexi/pdlearn/mydriver.py", line 151, in get_cookie_from_network
    self.driver.get("https://pc.xuexi.cn/points/login.html")
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.494
  (Session info: headless chrome=97.0.4692.99)

**Comment by paulownia99** [comment]
可以分享下Python代码吗，感谢 paulownia#hotmail
